# Generated by Django 2.1 on 2018-11-09 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('author_name', models.TextField()),
                ('author_website', models.TextField()),
                ('short_description', models.TextField()),
                ('content', models.TextField()),
            ],
        ),
    ]
