# Generated by Django 2.1 on 2018-11-09 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_post_created_on'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='genre',
            field=models.TextField(default='Poem'),
        ),
    ]
